Repository ltzmax/maxcogs, pull requests merged in 2021-10, with the labels that each got.

#20 [nekos, spaceimages and veryfun] Use the cog-wide session in commands.
  nekos/nekos.py
  spaceimages/spaceimages.py
  veryfun/veryfun.py
Labels: enhancement, Bug fix, hacktober

#21 Use nekosbest package rather than using aiohttp
  nekos/info.json
  nekos/nekos.py
  requirements.txt
Labels: enhancement, hacktoberfest-accepted

#22 Update README.md
  README.md
Labels: Bug fix, hacktoberfest-accepted

#26 [OnConnect] Fix webhook issue when using multiple bots.
  onconnect/commands.py
  onconnect/info.json
  onconnect/onconnect.py
Labels: Bug fix, hacktoberfest-accepted
